/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1;

import java.awt.Color;
import java.awt.Font;
import static java.lang.System.exit;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Arley
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
     FormatoRegistro formatoCrearUsuario = new FormatoRegistro();
     FormatoEquipo formatoCrearEquipo = new FormatoEquipo();
     FormatoServicio formatoCrearServicio = new FormatoServicio();
     FormatoRegistro formatoLeerUsuario = new FormatoRegistro();
     FormatoEquipo formatoLeerEquipo = new FormatoEquipo();
     FormatoServicio formatoLeerServicio = new FormatoServicio();
     FormatoRegistro formatoEditarUsuario = new FormatoRegistro();
     FormatoEquipo formatoEditarEquipo = new FormatoEquipo();
     FormatoServicio formatoEditarServicio = new FormatoServicio();
     javax.swing.DefaultListModel modelo = new javax.swing.DefaultListModel();
     
     
    public Interfaz() {
        initComponents();
        jPanel1.setVisible(true);
       titulo.setText("La Clinica del PC");
        formatoCrearUsuario.setVisible(false);
        crearUsuario.setVisible(false);
        crearEquipo.setVisible(false);        // TODO add your handling code here:
        crearServicio.setVisible(false);        // TODO add your handling code here:
        leerUsuario.setVisible(false);        // TODO add your handling code here:
        leerEquipo.setVisible(false);        // TODO add your handling code here:
        leerServicio.setVisible(false);        // TODO add your handling code here:
        editarUsuario.setVisible(false);        // TODO add your handling code here:
        editarEquipo.setVisible(false);        // TODO add your handling code here:
        editarServicio.setVisible(false);        // TODO add your handling code here:
        borrarUsuario.setVisible(false);        // TODO add your handling code here:
        borrarEquipo.setVisible(false);        // TODO add your handling code here:
        borrarServicio.setVisible(false);        // TODO add your handling code here:

       
        modelo.addElement("Arley Hoyos");    // !!!!CREACION DE LA LISTA!!!!!, TODO SE AGREGA AL MODELO Y LUEGO SE LE PASA EL MODELO A LA LISTA
        modelo.addElement("Pepito Perez");
        modelo.addElement("Elsa Pato");
        Users usuario = new Users();                // ejemplo de pasar datos desde la clase users
        usuario.identificacion = "Lalo Cota";   
        modelo.addElement(usuario.identificacion);
        lista.setModel(modelo);        //AL FINAL SIEMPRE SE DEBE PASAR EL MODELO A LA LISTA


        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jFrame1 = new javax.swing.JFrame();
        jOptionPane1 = new javax.swing.JOptionPane();
        jMenuItem2 = new javax.swing.JMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        titulo = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        crearUsuario = new javax.swing.JButton();
        crearEquipo = new javax.swing.JButton();
        crearServicio = new javax.swing.JButton();
        leerUsuario = new javax.swing.JButton();
        leerEquipo = new javax.swing.JButton();
        leerServicio = new javax.swing.JButton();
        editarUsuario = new javax.swing.JButton();
        editarEquipo = new javax.swing.JButton();
        editarServicio = new javax.swing.JButton();
        borrarUsuario = new javax.swing.JButton();
        borrarEquipo = new javax.swing.JButton();
        borrarServicio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>(modelo);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuUsuarios = new javax.swing.JMenuItem();
        menuEquipos = new javax.swing.JMenuItem();
        menuServicios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("jRadioButtonMenuItem3");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenuItem2.setText("jMenuItem2");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        titulo.setText("label1");

        crearUsuario.setText("Crear Usuario");
        crearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearUsuarioActionPerformed(evt);
            }
        });

        crearEquipo.setText("Crear Equipo");
        crearEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearEquipoActionPerformed(evt);
            }
        });

        crearServicio.setText("Crear Servicio");
        crearServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearServicioActionPerformed(evt);
            }
        });

        leerUsuario.setText("Leer Usuario");
        leerUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerUsuarioActionPerformed(evt);
            }
        });

        leerEquipo.setText("Leer Equipo");
        leerEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerEquipoActionPerformed(evt);
            }
        });

        leerServicio.setText("Leer Servicio");
        leerServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerServicioActionPerformed(evt);
            }
        });

        editarUsuario.setText("Editar Usuario");
        editarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarUsuarioActionPerformed(evt);
            }
        });

        editarEquipo.setText("Editar Equipo");
        editarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarEquipoActionPerformed(evt);
            }
        });

        editarServicio.setText("Editar Servicio");
        editarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarServicioActionPerformed(evt);
            }
        });

        borrarUsuario.setText("Borrar Usuario");
        borrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarUsuarioActionPerformed(evt);
            }
        });

        borrarEquipo.setText("Borrar Equipo");
        borrarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarEquipoActionPerformed(evt);
            }
        });

        borrarServicio.setText("Borrar Servicio");
        borrarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarServicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(leerUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(crearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(crearEquipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crearServicio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(borrarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(leerEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(leerServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(editarEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(borrarEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(editarServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(borrarServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearUsuario)
                    .addComponent(crearEquipo)
                    .addComponent(crearServicio))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leerUsuario)
                    .addComponent(leerEquipo)
                    .addComponent(leerServicio))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarUsuario)
                    .addComponent(editarEquipo)
                    .addComponent(editarServicio))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrarUsuario)
                    .addComponent(borrarEquipo)
                    .addComponent(borrarServicio))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        lista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lista);

        jMenu1.setText("Menu");

        menuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menuUsuarios.setText("Usuarios");
        menuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(menuUsuarios);

        menuEquipos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menuEquipos.setText("Equipos");
        menuEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEquiposActionPerformed(evt);
            }
        });
        jMenu1.add(menuEquipos);

        menuServicios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuServicios.setText("Servicios");
        menuServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuServiciosActionPerformed(evt);
            }
        });
        jMenu1.add(menuServicios);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");

        jMenuItem5.setText("Salir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem4.setText("Creditos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
JOptionPane.showMessageDialog(null, "Creditos: \n\n"+"Ricardo R. Smirnov"+"\nLuis Alejandro Castrillón Vanegas\n" +
"Yair Arley Hoyos Alzate\n" +
"Deibison Steven Grajales Palacio\n" 
);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void menuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuariosActionPerformed

titulo.setText("Usuarios");
crearUsuario.setVisible(true);
crearEquipo.setVisible(false);        // TODO add your handling code here:
crearServicio.setVisible(false);        // TODO add your handling code here:
leerUsuario.setVisible(true);        // TODO add your handling code here:
leerEquipo.setVisible(false);        // TODO add your handling code here:
leerServicio.setVisible(false);        // TODO add your handling code here:
editarUsuario.setVisible(true);        // TODO add your handling code here:
editarEquipo.setVisible(false);        // TODO add your handling code here:
editarServicio.setVisible(false);        // TODO add your handling code here:
borrarUsuario.setVisible(true);        // TODO add your handling code here:
borrarEquipo.setVisible(false);        // TODO add your handling code here:
borrarServicio.setVisible(false);        // TODO add your handling code here:

        //CODIGO DE ACTUALIZAR LA LISTA CON LOS USUARIOS

    }//GEN-LAST:event_menuUsuariosActionPerformed

    private void crearEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearEquipoActionPerformed
formatoCrearEquipo.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_crearEquipoActionPerformed

    private void crearServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearServicioActionPerformed
       formatoCrearServicio.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_crearServicioActionPerformed

    private void leerUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerUsuarioActionPerformed
formatoLeerUsuario.setVisible(true);   

    }//GEN-LAST:event_leerUsuarioActionPerformed

    private void menuServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuServiciosActionPerformed
titulo.setText("Servicios");
crearUsuario.setVisible(false);
crearEquipo.setVisible(false);        // TODO add your handling code here:
crearServicio.setVisible(true);        // TODO add your handling code here:
leerUsuario.setVisible(false);        // TODO add your handling code here:
leerEquipo.setVisible(false);        // TODO add your handling code here:
leerServicio.setVisible(true);        // TODO add your handling code here:
editarUsuario.setVisible(false);        // TODO add your handling code here:
editarEquipo.setVisible(false);        // TODO add your handling code here:
editarServicio.setVisible(true);        // TODO add your handling code here:
borrarUsuario.setVisible(false);        // TODO add your handling code here:
borrarEquipo.setVisible(false);        // TODO add your handling code here:
borrarServicio.setVisible(true);        // TODO add your handling code here:

            //CODIGO ACTUALIZAR LISTA CON SERVICIOS
    }//GEN-LAST:event_menuServiciosActionPerformed

    private void menuEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEquiposActionPerformed
titulo.setText("Equipos");
crearUsuario.setVisible(false);
crearEquipo.setVisible(true);        // TODO add your handling code here:
crearServicio.setVisible(false);        // TODO add your handling code here:
leerUsuario.setVisible(false);        // TODO add your handling code here:
leerEquipo.setVisible(true);        // TODO add your handling code here:
leerServicio.setVisible(false);        // TODO add your handling code here:
editarUsuario.setVisible(false);        // TODO add your handling code here:
editarEquipo.setVisible(true);        // TODO add your handling code here:
editarServicio.setVisible(false);        // TODO add your handling code here:
borrarUsuario.setVisible(false);        // TODO add your handling code here:
borrarEquipo.setVisible(true);        // TODO add your handling code here:
borrarServicio.setVisible(false);        // TODO add your handling code here:

        //CODIGO ACTUALIZAR LISTA PONIENDO TODA LA LISTA DE EQUIPOS
    }//GEN-LAST:event_menuEquiposActionPerformed

    private void crearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearUsuarioActionPerformed
formatoCrearUsuario.setVisible(true);        //ESTE NO NECESITA MAS CODIGO

    }//GEN-LAST:event_crearUsuarioActionPerformed

    private void editarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarUsuarioActionPerformed
formatoEditarUsuario.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_editarUsuarioActionPerformed

    private void borrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarUsuarioActionPerformed
      // Mensaje de si esta seguro borrar y poner al usuario como inactivo... no se borra realmente
    }//GEN-LAST:event_borrarUsuarioActionPerformed

    private void leerEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerEquipoActionPerformed
formatoLeerEquipo.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_leerEquipoActionPerformed

    private void editarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarEquipoActionPerformed
formatoEditarEquipo.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_editarEquipoActionPerformed

    private void leerServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerServicioActionPerformed
formatoLeerServicio.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_leerServicioActionPerformed

    private void editarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarServicioActionPerformed
formatoEditarServicio.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_editarServicioActionPerformed

    private void borrarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarEquipoActionPerformed
// Mensaje de si esta seguro borrar y poner al equipo como inactivo... no se borra realmente        // TODO add your handling code here:
    }//GEN-LAST:event_borrarEquipoActionPerformed

    private void borrarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarServicioActionPerformed
// Mensaje de si esta seguro borrar y poner al servicio como inactivo... no se borra realmente        // TODO add your handling code here:
    }//GEN-LAST:event_borrarServicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            
                
            }
                    });
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarEquipo;
    private javax.swing.JButton borrarServicio;
    private javax.swing.JButton borrarUsuario;
    private javax.swing.JButton crearEquipo;
    private javax.swing.JButton crearServicio;
    private javax.swing.JButton crearUsuario;
    private javax.swing.JButton editarEquipo;
    private javax.swing.JButton editarServicio;
    private javax.swing.JButton editarUsuario;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton leerEquipo;
    private javax.swing.JButton leerServicio;
    private javax.swing.JButton leerUsuario;
    private javax.swing.JList<String> lista;
    private javax.swing.JMenuItem menuEquipos;
    private javax.swing.JMenuItem menuServicios;
    private javax.swing.JMenuItem menuUsuarios;
    private java.awt.Label titulo;
    // End of variables declaration//GEN-END:variables
}
