/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1;

import static java.lang.System.exit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Arley
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
     FormatoRegistro formato = new FormatoRegistro();
    public Interfaz() {
        initComponents();
        jPanel1.setVisible(false);
       
        formato.setVisible(false);


        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jFrame1 = new javax.swing.JFrame();
        jOptionPane1 = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        textBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonBuscarUsuario = new javax.swing.JButton();
        botonBuscarEquipo = new javax.swing.JButton();
        botonBuscarServicio = new javax.swing.JButton();
        botonEliminarEquipo = new javax.swing.JButton();
        botonEliminarUsuario = new javax.swing.JButton();
        botonEliminarServicio = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaMuestra = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        eliminarUsuario = new javax.swing.JMenu();
        registrarUsuario = new javax.swing.JMenuItem();
        buscarUsuario = new javax.swing.JMenuItem();
        eliminaUsuario = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        registraEquipo = new javax.swing.JMenuItem();
        buscarEquipo = new javax.swing.JMenuItem();
        eliminaEquipo = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        registrarServicio = new javax.swing.JMenuItem();
        buscarServicio = new javax.swing.JMenuItem();
        eliminarServicio = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("jRadioButtonMenuItem3");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("ID del Usuario:");

        jLabel2.setText("Buscar Usuario");

        botonBuscarUsuario.setText("Buscar");
        botonBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarUsuarioActionPerformed(evt);
            }
        });

        botonBuscarEquipo.setText("Buscar");
        botonBuscarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarEquipoActionPerformed(evt);
            }
        });

        botonBuscarServicio.setText("Buscar");
        botonBuscarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarServicioActionPerformed(evt);
            }
        });

        botonEliminarEquipo.setText("Eliminar");
        botonEliminarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarEquipoActionPerformed(evt);
            }
        });

        botonEliminarUsuario.setText("Eliminar");
        botonEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarUsuarioActionPerformed(evt);
            }
        });

        botonEliminarServicio.setText("Eliminar");
        botonEliminarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarServicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(botonBuscarUsuario)
                                            .addComponent(botonBuscarServicio))
                                        .addGap(18, 18, 18)
                                        .addComponent(botonEliminarUsuario))
                                    .addComponent(botonEliminarServicio, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(textBuscar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonBuscarEquipo)
                        .addGap(18, 18, 18)
                        .addComponent(botonEliminarEquipo)))
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscarEquipo)
                    .addComponent(botonEliminarEquipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonEliminarUsuario)
                            .addComponent(botonBuscarServicio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEliminarServicio))
                    .addComponent(botonBuscarUsuario, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        areaMuestra.setColumns(20);
        areaMuestra.setRows(5);
        jScrollPane2.setViewportView(areaMuestra);

        jMenu1.setText("Menu");

        eliminarUsuario.setText("Usuarios");

        registrarUsuario.setText("Registrar");
        registrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarUsuarioActionPerformed(evt);
            }
        });
        eliminarUsuario.add(registrarUsuario);

        buscarUsuario.setText("Buscar");
        buscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarUsuarioActionPerformed(evt);
            }
        });
        eliminarUsuario.add(buscarUsuario);

        eliminaUsuario.setText("Eliminar");
        eliminaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaUsuarioActionPerformed(evt);
            }
        });
        eliminarUsuario.add(eliminaUsuario);

        jMenu1.add(eliminarUsuario);

        jMenu4.setText("Equipos");

        registraEquipo.setText("Registrar");
        registraEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registraEquipoActionPerformed(evt);
            }
        });
        jMenu4.add(registraEquipo);

        buscarEquipo.setText("Buscar");
        buscarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarEquipoActionPerformed(evt);
            }
        });
        jMenu4.add(buscarEquipo);

        eliminaEquipo.setText("Eliminar");
        eliminaEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaEquipoActionPerformed(evt);
            }
        });
        jMenu4.add(eliminaEquipo);

        jMenu1.add(jMenu4);

        jMenu5.setText("Servicios");

        registrarServicio.setText("Registrar");
        registrarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarServicioActionPerformed(evt);
            }
        });
        jMenu5.add(registrarServicio);

        buscarServicio.setText("Buscar");
        buscarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarServicioActionPerformed(evt);
            }
        });
        jMenu5.add(buscarServicio);

        eliminarServicio.setText("Eliminar");
        eliminarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarServicioActionPerformed(evt);
            }
        });
        jMenu5.add(eliminarServicio);

        jMenu1.add(jMenu5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");

        jMenuItem5.setText("Salir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem4.setText("Creditos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 26, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarUsuarioActionPerformed
       
        jPanel1.setVisible(true);        // TODO add your handling code here:
        jLabel1.setText("ID de Usuario:");
        jLabel2.setText("Buscar Usuario");
        botonBuscarUsuario.setVisible(true);
        botonBuscarEquipo.setVisible(false);
        botonBuscarServicio.setVisible(false);
        botonEliminarUsuario.setVisible(false);
        botonEliminarEquipo.setVisible(false);
        botonEliminarServicio.setVisible(false);
        


    }//GEN-LAST:event_buscarUsuarioActionPerformed

    private void eliminaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaUsuarioActionPerformed
  // TODO add your handling code here:
       jPanel1.setVisible(true);        // TODO add your handling code here:
        jLabel1.setText("ID de Usuario:");
        jLabel2.setText("Eliminar Usuario");
                botonBuscarUsuario.setVisible(false);
        botonBuscarEquipo.setVisible(false);
        botonBuscarServicio.setVisible(false);
        botonEliminarUsuario.setVisible(true);
        botonEliminarEquipo.setVisible(false);
        botonEliminarServicio.setVisible(false);
    }//GEN-LAST:event_eliminaUsuarioActionPerformed

    private void buscarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarEquipoActionPerformed
              jPanel1.setVisible(true);        // TODO add your handling code here:
        jLabel1.setText("Codigo del Equipo:");
        jLabel2.setText("Buscar Equipo");
                botonBuscarUsuario.setVisible(false);
        botonBuscarEquipo.setVisible(true);
        botonBuscarServicio.setVisible(false);
        botonEliminarUsuario.setVisible(false);
        botonEliminarEquipo.setVisible(false);
        botonEliminarServicio.setVisible(false);

    }//GEN-LAST:event_buscarEquipoActionPerformed

    private void eliminarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarServicioActionPerformed
    jPanel1.setVisible(true);        // TODO add your handling code here:
        jLabel1.setText("Codigo del Servicio:");
        jLabel2.setText("Eliminar Servicio");        // TODO add your handling code here:
                botonBuscarUsuario.setVisible(false);
        botonBuscarEquipo.setVisible(false);
        botonBuscarServicio.setVisible(false);
        botonEliminarUsuario.setVisible(false);
        botonEliminarEquipo.setVisible(false);
        botonEliminarServicio.setVisible(true);
    }//GEN-LAST:event_eliminarServicioActionPerformed

    private void botonBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBuscarUsuarioActionPerformed

    private void buscarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarServicioActionPerformed
        // TODO add your handling code here:
               jPanel1.setVisible(true);        // TODO add your handling code here:
        jLabel1.setText("Codigo del Servicio:");
        jLabel2.setText("Buscar Servicio");
                        botonBuscarUsuario.setVisible(false);
        botonBuscarEquipo.setVisible(false);
        botonBuscarServicio.setVisible(true);
        botonEliminarUsuario.setVisible(false);
        botonEliminarEquipo.setVisible(false);
        botonEliminarServicio.setVisible(false);
    }//GEN-LAST:event_buscarServicioActionPerformed

    private void registrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarUsuarioActionPerformed

        // TODO add your handling code here:
        
        formato.setVisible(true);
    }//GEN-LAST:event_registrarUsuarioActionPerformed

    private void eliminaEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaEquipoActionPerformed
          jPanel1.setVisible(true);        // TODO add your handling code here:
        jLabel1.setText("Codigo del Equipo:");
        jLabel2.setText("Eliminar Equipo");        // TODO add your handling code here:
                        botonBuscarUsuario.setVisible(false);
        botonBuscarEquipo.setVisible(false);
        botonBuscarServicio.setVisible(false);
        botonEliminarUsuario.setVisible(false);
        botonEliminarEquipo.setVisible(true);
        botonEliminarServicio.setVisible(false);
    }//GEN-LAST:event_eliminaEquipoActionPerformed

    private void registraEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registraEquipoActionPerformed
        // TODO add your handling code here:
        formato.setVisible(true);
    }//GEN-LAST:event_registraEquipoActionPerformed

    private void botonBuscarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBuscarEquipoActionPerformed

    private void botonBuscarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBuscarServicioActionPerformed

    private void botonEliminarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarEquipoActionPerformed

    private void botonEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarUsuarioActionPerformed

    private void botonEliminarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarServicioActionPerformed

    private void registrarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarServicioActionPerformed
        // TODO add your handling code here:
        formato.setVisible(true);
    }//GEN-LAST:event_registrarServicioActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
JOptionPane.showMessageDialog(null, "Creditos: \n\n"+"Ricardo R. Smirnov"+"\nLuis Alejandro Castrillón Vanegas\n" +
"Yair Arley Hoyos Alzate\n" +
"Deibison Steven Grajales Palacio\n" 
);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            
                
            }
                    });
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaMuestra;
    private javax.swing.JButton botonBuscarEquipo;
    private javax.swing.JButton botonBuscarServicio;
    private javax.swing.JButton botonBuscarUsuario;
    private javax.swing.JButton botonEliminarEquipo;
    private javax.swing.JButton botonEliminarServicio;
    private javax.swing.JButton botonEliminarUsuario;
    private javax.swing.JMenuItem buscarEquipo;
    private javax.swing.JMenuItem buscarServicio;
    private javax.swing.JMenuItem buscarUsuario;
    private javax.swing.JMenuItem eliminaEquipo;
    private javax.swing.JMenuItem eliminaUsuario;
    private javax.swing.JMenuItem eliminarServicio;
    private javax.swing.JMenu eliminarUsuario;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem registraEquipo;
    private javax.swing.JMenuItem registrarServicio;
    private javax.swing.JMenuItem registrarUsuario;
    private javax.swing.JTextField textBuscar;
    // End of variables declaration//GEN-END:variables
}
